a:6:{s:8:"feedinfo";a:3:{s:4:"type";s:3:"RSS";s:7:"version";s:3:"2.0";s:8:"encoding";s:5:"UTF-8";}s:4:"info";a:4:{s:4:"link";a:1:{s:9:"alternate";a:1:{i:0;s:22:"http://tawanetwork.com";}}s:5:"title";s:15:"TURISMO EN PERU";s:11:"description";s:32:"PERU, país mágico y milenario.";s:8:"language";s:2:"en";}s:5:"items";a:1:{i:0;O:14:"simplepie_item":1:{s:4:"data";a:8:{s:5:"title";s:39:"Machu Picchu, Nueva Maravilla del Mundo";s:7:"encoded";s:3070:"<p><a href='http://tawanetwork.com/machu-picchu-nueva-maravilla-del-mundo.html/la-gran-muralla-china/' rel='attachment wp-att-33' title='La Gran Muralla China'><img src='http://tawanetwork.com/wp-content/uploads/2007/07/muralla-china.thumbnail.jpg' alt='La Gran Muralla China' /></a></p>
<p><a href='http://tawanetwork.com/machu-picchu-nueva-maravilla-del-mundo.html/petra-de-jordania/' rel='attachment wp-att-34' title='Petra de Jordania.'><img src='http://tawanetwork.com/wp-content/uploads/2007/07/petra.thumbnail.jpg' alt='Petra de Jordania.' /></a></p>
<p><a href='http://tawanetwork.com/machu-picchu-nueva-maravilla-del-mundo.html/cristo-redentor-de-brasil/' rel='attachment wp-att-35' title='Cristo Redentor de Brasil'><img src='http://tawanetwork.com/wp-content/uploads/2007/07/cristo.thumbnail.jpg' alt='Cristo Redentor de Brasil' /></a></p>
<p><a href='http://tawanetwork.com/machu-picchu-nueva-maravilla-del-mundo.html/machu-picchu-peru/' rel='attachment wp-att-36' title='Machu Picchu - Perú'><img src='http://tawanetwork.com/wp-content/uploads/2007/07/machupicchu.thumbnail.jpg' alt='Machu Picchu - Perú' /></a></p>
<p><a href='http://tawanetwork.com/machu-picchu-nueva-maravilla-del-mundo.html/chichen-itza-mexico/' rel='attachment wp-att-37' title='Chichen Itza - Mexico'><img src='http://tawanetwork.com/wp-content/uploads/2007/07/chichen-itza.thumbnail.jpg' alt='Chichen Itza - Mexico' /></a></p>
<p><a href='http://tawanetwork.com/machu-picchu-nueva-maravilla-del-mundo.html/el-coliseo-romano/' rel='attachment wp-att-38' title='El Coliseo Romano'><img src='http://tawanetwork.com/wp-content/uploads/2007/07/coliseo-romano.thumbnail.jpg' alt='El Coliseo Romano' /></a></p>
<p><a href='http://tawanetwork.com/machu-picchu-nueva-maravilla-del-mundo.html/el-taj-mahal-jordania/' rel='attachment wp-att-39' title='El Taj Mahal - Jordania'><img src='http://tawanetwork.com/wp-content/uploads/2007/07/taj-mahal.thumbnail.jpg' alt='El Taj Mahal - Jordania' /></a></p>
<p><a href='http://tawanetwork.com/machu-picchu-nueva-maravilla-del-mundo.html/machu-picchu-peru-2/' rel='attachment wp-att-40' title='Machu Picchu - Perú'><img src='http://tawanetwork.com/wp-content/uploads/2007/07/machupicchu-1.thumbnail.jpg' alt='Machu Picchu - Perú' /></a></p>
<p>A pesar que la elección de las Siete Nuevas maravillas del Mundo, no ha tenido el respaldo de la UNESCO, <a href="http://es.wikipedia.org/wiki/Machu_Picchu">Machu Picchu</a>, ha sido elegida una de las siete nuevas maravillas del mundo, junto a:<br />
<a href="http://es.wikipedia.org/wiki/Gran_Muralla_China">La Muralla China</a>,<br />
<a href="http://es.wikipedia.org/wiki/Petra">Petra de Jordania</a>,<br />
<a href="http://es.wikipedia.org/wiki/Cristo_Redentor_(R%C3%ADo_de_Janeiro)">El Cristo Redentor de Brasil</a>,<br />
<a href="http://es.wikipedia.org/wiki/Chich%C3%A9n_Itz%C3%A1">Chichen Itza de Mexico</a>,<br />
<a href="http://es.wikipedia.org/wiki/Coliseo_de_Roma">El Coliseo Romano de Italia</a>,<br />
<a href="http://es.wikipedia.org/wiki/Taj_Mahal">El Taj Mahal de La India</a>.</p>";s:11:"description";s:336:"A pesar que la elección de las Siete Nuevas maravillas del Mundo, no ha tenido el respaldo de la UNESCO, Machu Picchu, ha sido elegida una de las siete nuevas maravillas del mundo, junto a:
La Muralla China,
Petra de Jordania,
El Cristo Redentor de Brasil,
Chichen Itza de Mexico,
El Coliseo Romano de Italia,
El Taj Mahal de La India.";s:4:"link";a:1:{s:9:"alternate";a:1:{i:0;s:66:"http://tawanetwork.com/machu-picchu-nueva-maravilla-del-mundo.html";}}s:4:"guid";a:2:{s:9:"permalink";b:0;s:4:"data";s:66:"http://tawanetwork.com/machu-picchu-nueva-maravilla-del-mundo.html";}s:7:"pubdate";i:1184214032;s:8:"category";a:1:{i:0;s:19:"Peru - Machu Picchu";}s:7:"creator";a:1:{i:0;O:16:"simplepie_author":3:{s:4:"name";s:16:"Vicente Góngora";s:4:"link";N;s:5:"email";N;}}}}}s:3:"url";s:28:"http://tawanetwork.com/feed/";s:13:"last-modified";s:29:"Thu, 12 Jul 2007 04:50:48 GMT";s:4:"etag";s:34:""38e3b8cfc921e59386a1b42b1360612a"";}